# Generated by Django 4.2.13 on 2024-05-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_category_options_alter_expense_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-pk']},
        ),
    ]
