# Generated by Django 4.2.13 on 2024-06-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_category_name_en_category_name_es_category_name_ja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category_es',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category_ja',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description_ja',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='name_ja',
        ),
    ]
