# Generated by Django 4.2.13 on 2024-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expense_category_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category_en',
            field=models.CharField(max_length=255, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category_es',
            field=models.CharField(max_length=255, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='category'),
        ),
    ]
