# Generated by Django 4.2.13 on 2024-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='currency',
            field=models.CharField(blank=True, default='USD - United States Dollar', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=255),
        ),
    ]
