# Generated by Django 4.2.13 on 2024-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alter_userpreferences_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ja', 'Japanese')], default='en', max_length=10),
        ),
    ]
