# Generated by Django 4.2.13 on 2024-06-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_amount_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='income',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='income',
            name='description_ja',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='income',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='income',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='income',
            name='name_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='income',
            name='source_en',
            field=models.CharField(max_length=255, null=True, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='income',
            name='source_es',
            field=models.CharField(max_length=255, null=True, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='income',
            name='source_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='source',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='name_ja',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
