# Generated by Django 4.2.13 on 2024-06-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_income_description_en_income_description_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description_ja',
        ),
        migrations.RemoveField(
            model_name='income',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='income',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='income',
            name='name_ja',
        ),
        migrations.RemoveField(
            model_name='income',
            name='source_en',
        ),
        migrations.RemoveField(
            model_name='income',
            name='source_es',
        ),
        migrations.RemoveField(
            model_name='income',
            name='source_ja',
        ),
    ]
