# Generated by Django 4.2.13 on 2024-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_remove_income_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='source_en',
            field=models.CharField(max_length=255, null=True, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='income',
            name='source_es',
            field=models.CharField(max_length=255, null=True, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='income',
            name='source_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='source'),
        ),
    ]
